package main

// WsClientConfig configuration struct
// This struct is usually automatically generated by EasyCfg, manually defined here for example
type WsClientConfig struct {
	General General `yaml:"general" mapstructure:"general"`
	Redis   Redis   `yaml:"redis" mapstructure:"redis"`
	Logger  Logger  `yaml:"logger" mapstructure:"logger"`
}

// General nested struct
type General struct {
	Type         string            `yaml:"type" mapstructure:"type"`
	Server       GeneralServer     `yaml:"server" mapstructure:"server"`
	WsListenPort int               `yaml:"ws_listen_port" mapstructure:"ws_listen_port"`
	Subscriber   GeneralSubscriber `yaml:"subscriber" mapstructure:"subscriber"`
}

// GeneralServer nested struct
type GeneralServer struct {
	Port string `yaml:"port" mapstructure:"port"`
}

// GeneralSubscriber nested struct
type GeneralSubscriber struct {
	Type    string `yaml:"type" mapstructure:"type"`
	RpcPort int    `yaml:"rpc_port" mapstructure:"rpc_port"`
}

// Redis nested struct
type Redis struct {
	Addrs    []string `yaml:"addrs" mapstructure:"addrs"`
	Password string   `yaml:"password" mapstructure:"password"`
}

// Logger nested struct
type Logger struct {
	Path  string `yaml:"path" mapstructure:"path"`
	Level string `yaml:"level" mapstructure:"level"`
}
